In [ ]:
DATA_PATH = '../data'

In [2]:
import pandas as pd
from scipy.io.arff import loadarff 

raw_data = loadarff(f'{DATA_PATH}/china.arff')
df_data = pd.DataFrame(raw_data[0])

In [3]:
df_data.head()

,ID,AFP,Input,Output,Enquiry,File,Interface,Added,Changed,Deleted,PDR_AFP,PDR_UFP,NPDR_AFP,NPDU_UFP,Resource,Dev.Type,Duration,N_effort,Effort
0,1.0,1587.0,774.0,260.0,340.0,128.0,0.0,1502.0,0.0,0.0,4.7,5.0,4.7,5.0,4.0,0.0,4.0,7490.0,7490.0
1,2.0,260.0,9.0,4.0,3.0,193.0,41.0,51.0,138.0,61.0,16.0,16.6,16.0,16.6,2.0,0.0,17.0,4150.0,4150.0
2,3.0,152.0,25.0,33.0,28.0,42.0,35.0,163.0,0.0,0.0,4.4,4.1,4.4,4.1,1.0,0.0,9.0,668.0,668.0
3,4.0,252.0,151.0,28.0,8.0,39.0,0.0,69.0,153.0,4.0,12.8,14.3,15.5,17.3,1.0,0.0,4.0,3901.0,3238.0
4,5.0,292.0,93.0,0.0,194.0,20.0,0.0,0.0,307.0,0.0,10.3,9.8,12.4,11.7,1.0,0.0,13.0,3607.0,2994.0